const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n],Request,Response,console:{log(){},error(){}},process:{env:{OPENAI_API_KEY:'test',NEXT_PUBLIC_SUPABASE_URL:'test',NEXT_PUBLIC_SUPABASE_ANON_KEY:'test'}}});return exports;}
const api=load('lib/ai-actions.ts');
const id=n=>`${n}`.repeat(8)+'-'+`${n}`.repeat(4)+'-'+`${n}`.repeat(4)+'-'+`${n}`.repeat(4)+'-'+`${n}`.repeat(12);
const args={customer_name:'Test',customer_phone:'2025550100',customer_email:null,service_name:'Cut',date:'2026-10-05',time:'10:00'};
const receipt={success:true,appointment_id:id(1),customer_id:id(2),business_id:id(3),service_id:id(4),service:'Cut',date:args.date,time:'10:00:00',status:'Booked'};
const call=(value=args)=>({type:'function_call',name:'book_appointment',arguments:JSON.stringify(value)});
function harness({output=[call()],data=receipt,rpcError=false,smsFailure=false,smsThrow=false,services=[{id:id(4),name:'Cut',duration_minutes:30,is_active:true}],final='throw',prior=null}={}){
 const events=[];let rpcArgs;
 const db={from:table=>{const q={};for(const m of ['select','eq','order','limit'])q[m]=()=>q;q.maybeSingle=async()=>({data:table==='business_profiles'?{business_name:'Test',business_hours:'{}'}:table==='appointment_actions'?prior:{}});q.then=resolve=>Promise.resolve({data:table==='services'?services:[]}).then(resolve);return q;},rpc:async(name,params)=>{if(name==='claim_appointment_notification')return{data:{claimed:true,id:id(6),token:id(7),kind:'confirmation',payload:{phone:'2025550100',date:args.date,time:args.time}}};if(name==='finish_appointment_notification')return{data:true};events.push('rpc');rpcArgs=params;if(rpcError)return{error:{message:'secret'}};if(data.success===true)events.push('commit');return{data:{...data,changed:data.changed??true,replayed:data.replayed??false,action_id:id(6),action_type:'book',receipt_scope:'action_outcome',code:data.code||'APPLIED',completed_at:'2026-10-05T00:00:00Z',appointment:{id:data.appointment_id,business_id:data.business_id,status:data.status}}};}};
 class OpenAI{static APIError=class extends Error{};responses={create:async()=>{events.push('model');if(events.filter(x=>x==='model').length>1){if(final==='throw')throw Error('secret');return{output_text:'',output:[call()]};}return{output,output_text:'Your appointment was cancelled and booked.'};}};}
 const helpers=load('lib/appointment-actions.ts',{'node:crypto':require('node:crypto'),'./ai-actions':api,'./twilio':{sendSms:async()=>{assert.ok(events.includes('commit'));events.push('sms');if(smsThrow)throw Error('secret');return{success:!smsFailure,messageSid:'SM'+'0'.repeat(32)};}}});
 const route=load('app/api/ai/route.ts',{'openai':{default:OpenAI},'@/lib/ai-actions':api,'@/lib/appointment-actions':helpers,'@supabase/supabase-js':{createClient:()=>db},'next/server':{NextResponse:{json:(d,i)=>Response.json(d,i)}},'@/lib/business-context':{resolveBusinessContext:async()=>({success:true,context:{businessId:id(3),businessName:'Test',timezone:'America/Los_Angeles'}})},'@/lib/twilio':{sendSms:async()=>{assert.ok(events.includes('commit'));events.push('sms');if(smsThrow)throw Error('secret');return{success:!smsFailure};}}});
 return {events,get rpcArgs(){return rpcArgs;},run:async(mode)=>{const r=await route.POST(new Request('https://example.invalid/api/ai',{method:'POST',headers:{authorization:'Bearer test','idempotency-key':id(8)},body:JSON.stringify({message:'Book',mode})}));return{status:r.status,...await r.json()};}};
}
for(const action of ['booked','rescheduled','confirmed','cancelled'])test(`model-only ${action} text never returned`,async()=>{const h=harness({output:[{type:'message',text:`Appointment ${action}`}]});const r=await h.run();assert.equal(r.action,null);assert.match(r.reply,/No appointment change has been verified/);assert.ok(!h.events.includes('rpc'));});
for(const value of [null,{...args,customer_name:1},{...args,date:'2026-02-30'},{...args,time:'10:00evil'},{...args,customer_email:3}])test('malformed tool input fails without RPC',async()=>{const h=harness({output:[call(value)]});const r=await h.run();assert.equal(r.action,null);assert.ok(!h.events.includes('rpc'));});
test('ambiguous service does not mutate',async()=>{const h=harness({services:[{id:id(4),name:'Cut one'},{id:id(5),name:'Cut two'}]});const r=await h.run();assert.equal(r.action,null);assert.match(r.reply,/unambiguous/);assert.ok(!h.events.includes('rpc'));});
for(const change of [{success:'true'},{success:1},{appointment_id:''},{business_id:id(8)},{service_id:id(8)},{customer_id:null},{status:'Confirmed'},{date:'2026-10-06'},{time:'10:00:00.000001'},{service:''}])test('invalid receipt never creates action success',async()=>{const h=harness({data:{...receipt,...change}});const r=await h.run();assert.equal(r.action,null);assert.ok(!h.events.includes('sms'));});
test('RPC failure sanitized',async()=>{const h=harness({rpcError:true});const r=await h.run();assert.equal(r.action,null);assert.ok(!JSON.stringify(r).includes('secret'));});
for(const options of [{},{smsFailure:true},{smsThrow:true},{final:'throw'},{final:'empty-and-later-tool'}])test('committed receipt survives SMS failure; final model stage eliminated',async()=>{const h=harness(options);const r=await h.run();assert.equal(r.status,200);assert.equal(r.action.receipt.appointment_id,id(1));assert.match(r.reply,/booked successfully/);assert.equal(h.events.filter(x=>x==='model').length,1);assert.equal(h.rpcArgs.p_business_id,id(3));});
test('multiple booking calls rejected before mutation',async()=>{const h=harness({output:[call(),call()]});assert.equal((await h.run()).action,null);assert.ok(!h.events.includes('rpc'));});
test('unsupported tool rejected',async()=>{const h=harness({output:[{...call(),name:'cancel_appointment'}]});assert.match((await h.run()).reply,/not supported/);assert.ok(!h.events.includes('rpc'));});
test('preview cannot write or send SMS',async()=>{const h=harness();assert.match((await h.run('preview')).reply,/Preview only/);assert.ok(!h.events.includes('rpc'));assert.ok(!h.events.includes('sms'));});
test('PostgreSQL fractional zero representations compare exactly',()=>{for(const time of ['10:00','10:00:00','10:00:00.0','10:00:00.000000'])assert.ok(api.bookingReceipt({...receipt,time},id(3),id(4),args.date,args.time));for(const time of ['10:00:01','10:00:00.000001','10:00Z','24:00:00'])assert.equal(api.bookingReceipt({...receipt,time},id(3),id(4),args.date,args.time),null);});
test('unique normalized exact match and unique partial only',()=>{assert.equal(api.uniqueService([{name:' Cut '},{name:'Cut long'}],'cut').name,' Cut ');assert.equal(api.uniqueService([{name:'Cut long'}],'cut').name,'Cut long');assert.equal(api.uniqueService([{name:'Cut'},{name:'cut'}],'cut'),null);});

test('durable AI replay is reconciled before model interpretation and mutation',async()=>{
 const helpers=load('lib/appointment-actions.ts',{'node:crypto':require('node:crypto'),'./ai-actions':api,'./twilio':{}});
 const prior={action_type:'book',completed_at:'2026-10-05T00:00:00Z',request_payload:{operation:'ai_book',origin_hash:helpers.fingerprint({message:'Book'}),service_id:id(4),date:args.date,time:args.time},result:{...receipt,changed:true,replayed:false,action_id:id(6),action_type:'book',receipt_scope:'action_outcome',code:'APPLIED',appointment:{id:id(1),business_id:id(3),status:'Booked'}}};
 const h=harness({prior});const result=await h.run();assert.equal(result.status,200);assert.equal(result.action.replayed,true);assert.match(result.reply,/original booking/);assert.ok(!h.events.includes('model'));assert.ok(!h.events.includes('rpc'));
});
test('AI replay key cannot be reused for different message origin',async()=>{
 const h=harness({prior:{action_type:'book',request_payload:{operation:'ai_book',origin_hash:'different'}}});assert.equal((await h.run()).status,409);assert.ok(!h.events.includes('rpc'));assert.ok(!h.events.includes('model'));
});

for (const code of ['SLOT_CONFLICT','CLOSED','OUTSIDE_HOURS','INVALID_SERVICE','INVALID_HOURS']) test(`controlled AI rejection ${code} has no success or SMS`,async()=>{
 const h=harness({data:{success:false,changed:false,business_id:id(3),code,reason:'PRIVATE LEGACY TEXT'}});
 const r=await h.run();assert.equal(r.status,200);assert.equal(r.action,null);assert.equal(r.rejection.code,code);assert.equal(r.rejection.success,false);assert.equal(r.rejection.changed,false);assert.match(r.reply,/not booked/);assert.ok(!h.events.includes('sms'));assert.ok(!JSON.stringify(r).includes('PRIVATE'));assert.ok(!h.events.includes('commit'));
});
test('persisted rejected AI action replays before OpenAI/RPC/notification execution',async()=>{
 const helpers=load('lib/appointment-actions.ts',{'node:crypto':require('node:crypto'),'./ai-actions':api,'./twilio':{}});
 const prior={action_type:'book',completed_at:'2026-10-05T00:00:00Z',request_payload:{operation:'ai_book',origin_hash:helpers.fingerprint({message:'Book'})},result:{success:false,changed:false,action_id:id(6),action_type:'book',business_id:id(3),code:'SLOT_CONFLICT',receipt_scope:'action_outcome',replayed:false,completed_at:'2026-10-05T00:00:00Z'}};
 const h=harness({prior});const a=await h.run(),b=await h.run();assert.equal(a.rejection.replayed,true);assert.deepEqual(a.rejection,b.rejection);assert.equal(a.action,null);assert.match(a.reply,/original booking request was rejected/);assert.deepEqual(h.events,[]);
});
for(const change of [{success:'false'},{changed:true},{code:'INTERNAL_ERROR'},{code:'UNKNOWN'},{action_id:''},{business_id:id(9)},{completed_at:null}])test('malformed/unexpected rejection is not promoted to a business-rule receipt',()=>{
 const value={success:false,changed:false,action_id:id(6),action_type:'book',business_id:id(3),code:'SLOT_CONFLICT',receipt_scope:'action_outcome',replayed:false,completed_at:'2026-10-05T00:00:00Z',...change};
 assert.equal(api.bookingRejection(value,id(3)),null);
});
