const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n],Request,Response,console:{log(){},error(){}},process:{env:{OPENAI_API_KEY:'test',NEXT_PUBLIC_SUPABASE_URL:'test',NEXT_PUBLIC_SUPABASE_ANON_KEY:'test'}}});return exports;}
const api=load('lib/ai-actions.ts');
const id=n=>`${n}`.repeat(8)+'-'+`${n}`.repeat(4)+'-'+`${n}`.repeat(4)+'-'+`${n}`.repeat(4)+'-'+`${n}`.repeat(12);
const args={customer_name:'Test',customer_phone:'2025550100',customer_email:null,service_name:'Cut',date:'2026-10-05',time:'10:00'};
const receipt={success:true,appointment_id:id(1),customer_id:id(2),business_id:id(3),service_id:id(4),service:'Cut',date:args.date,time:'10:00:00',status:'Booked'};
const call=(value=args)=>({type:'function_call',name:'book_appointment',arguments:JSON.stringify(value)});
function harness({output=[call()],data=receipt,rpcError=false,smsFailure=false,smsThrow=false,services=[{id:id(4),name:'Cut',duration_minutes:30,is_active:true}],final='throw'}={}){
 const events=[];let rpcArgs;
 const db={from:table=>{const q={};for(const m of ['select','eq','order','limit'])q[m]=()=>q;q.maybeSingle=async()=>({data:table==='business_profiles'?{business_name:'Test',business_hours:'{}'}:{}});q.then=resolve=>Promise.resolve({data:table==='services'?services:[]}).then(resolve);return q;},rpc:async(name,params)=>{events.push('rpc');rpcArgs=params;if(rpcError)return{error:{message:'secret'}};if(data.success===true)events.push('commit');return{data};}};
 class OpenAI{static APIError=class extends Error{};responses={create:async()=>{events.push('model');if(events.filter(x=>x==='model').length>1){if(final==='throw')throw Error('secret');return{output_text:'',output:[call()]};}return{output,output_text:'Your appointment was cancelled and booked.'};}};}
 const route=load('app/api/ai/route.ts',{'openai':{default:OpenAI},'@/lib/ai-actions':api,'@supabase/supabase-js':{createClient:()=>db},'next/server':{NextResponse:{json:(d,i)=>Response.json(d,i)}},'@/lib/business-context':{resolveBusinessContext:async()=>({success:true,context:{businessId:id(3),businessName:'Test',timezone:'America/Los_Angeles'}})},'@/lib/twilio':{sendSms:async()=>{assert.ok(events.includes('commit'));events.push('sms');if(smsThrow)throw Error('secret');return{success:!smsFailure};}}});
 return {events,get rpcArgs(){return rpcArgs;},run:async(mode)=>{const r=await route.POST(new Request('https://example.invalid/api/ai',{method:'POST',headers:{authorization:'Bearer test'},body:JSON.stringify({message:'Book',mode})}));return{status:r.status,...await r.json()};}};
}
for(const action of ['booked','rescheduled','confirmed','cancelled'])test(`model-only ${action} text never returned`,async()=>{const h=harness({output:[{type:'message',text:`Appointment ${action}`}]});const r=await h.run();assert.equal(r.action,null);assert.match(r.reply,/No appointment change has been verified/);assert.ok(!h.events.includes('rpc'));});
for(const value of [null,{...args,customer_name:1},{...args,date:'2026-02-30'},{...args,time:'10:00evil'},{...args,customer_email:3}])test('malformed tool input fails without RPC',async()=>{const h=harness({output:[call(value)]});const r=await h.run();assert.equal(r.action,null);assert.ok(!h.events.includes('rpc'));});
test('ambiguous service does not mutate',async()=>{const h=harness({services:[{id:id(4),name:'Cut one'},{id:id(5),name:'Cut two'}]});const r=await h.run();assert.equal(r.action,null);assert.match(r.reply,/unambiguous/);assert.ok(!h.events.includes('rpc'));});
for(const change of [{success:'true'},{success:1},{appointment_id:''},{business_id:id(8)},{service_id:id(8)},{customer_id:null},{status:'Confirmed'},{date:'2026-10-06'},{time:'10:00:00.000001'},{service:''}])test('invalid receipt never creates action success',async()=>{const h=harness({data:{...receipt,...change}});const r=await h.run();assert.equal(r.action,null);assert.ok(!h.events.includes('sms'));});
test('RPC failure sanitized',async()=>{const h=harness({rpcError:true});const r=await h.run();assert.equal(r.action,null);assert.ok(!JSON.stringify(r).includes('secret'));});
for(const options of [{},{smsFailure:true},{smsThrow:true},{final:'throw'},{final:'empty-and-later-tool'}])test('committed receipt survives SMS failure; final model stage eliminated',async()=>{const h=harness(options);const r=await h.run();assert.equal(r.status,200);assert.equal(r.action.receipt.appointment_id,id(1));assert.match(r.reply,/booked successfully/);assert.equal(h.events.filter(x=>x==='model').length,1);assert.equal(h.rpcArgs.p_business_id,id(3));});
test('multiple booking calls rejected before mutation',async()=>{const h=harness({output:[call(),call()]});assert.equal((await h.run()).action,null);assert.ok(!h.events.includes('rpc'));});
test('unsupported tool rejected',async()=>{const h=harness({output:[{...call(),name:'cancel_appointment'}]});assert.match((await h.run()).reply,/not supported/);assert.ok(!h.events.includes('rpc'));});
test('preview cannot write or send SMS',async()=>{const h=harness();assert.match((await h.run('preview')).reply,/Preview only/);assert.ok(!h.events.includes('rpc'));assert.ok(!h.events.includes('sms'));});
test('PostgreSQL fractional zero representations compare exactly',()=>{for(const time of ['10:00','10:00:00','10:00:00.0','10:00:00.000000'])assert.ok(api.bookingReceipt({...receipt,time},id(3),id(4),args.date,args.time));for(const time of ['10:00:01','10:00:00.000001','10:00Z','24:00:00'])assert.equal(api.bookingReceipt({...receipt,time},id(3),id(4),args.date,args.time),null);});
test('unique normalized exact match and unique partial only',()=>{assert.equal(api.uniqueService([{name:' Cut '},{name:'Cut long'}],'cut').name,' Cut ');assert.equal(api.uniqueService([{name:'Cut long'}],'cut').name,'Cut long');assert.equal(api.uniqueService([{name:'Cut'},{name:'cut'}],'cut'),null);});
