const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const {fixture}=require('./support/working-fixture.cjs');const {as}=require('./support/pglite-db.cjs');
const uuid=()=>crypto.randomUUID(),H=3600000;
async function setup(t){const h=await fixture(t),target=await h.employee(),targetSession=await h.sessionFor(target),api=h.load('server/handlers/time-reports.ts'),reports=h.load('server/time-reports.ts');await h.db.query("update public.businesses set timezone='UTC' where id=$1",[h.business]);
 const input={startDate:'2026-03-03',endDate:'2026-03-03',employeeId:target,grouping:'day'};
 const json=async r=>({status:r.status,body:await r.json()});
 const get=(extra={},shared=false)=>api.GET(h.request('/api/management/time-reports?'+new URLSearchParams(Object.fromEntries(Object.entries({...input,...extra}).filter(([,v])=>v!==undefined))),{shared})).then(json);
 const exportCsv=(extra={},shared=false)=>api.EXPORT(new Request('https://zude.test/api/management/time-reports/export',{method:'POST',headers:{Authorization:'Bearer synthetic-account',...(shared?{'x-zude-device':h.deviceCredential,'x-zude-employee-session':h.sessionCredential}:{})},body:JSON.stringify({...input,...extra})})).then(json);
 const event=(type,stamp,kind=null)=>h.event(target,type,Date.parse(stamp),kind);
 const correct=async operations=>{const v=(await h.service.rpc('m06_ledger_read_versions',{p_business_id:h.business,p_employee_id:target})).data[0];return as(h.db,'service_role',"select public.m06_correct_employee_time($1,$2,$3,'account','owner',null,null,null,$4::jsonb,'Report regression',$5,$6,$7,true,null,null)",[h.business,target,h.account,JSON.stringify(operations),uuid(),Number(v.correctionRevision),v.originalWatermark]);};
 return {...h,target,targetSession,api,reports,input,get,exportCsv,event,correct};}
for(const role of ['staff','manager','owner'])test(`Reports ${role} authority, target hierarchy and tenant binding`,async t=>{const h=await setup(t);await h.db.query('update public.business_members set role=$1',[role]);assert.equal((await h.get()).status,role==='staff'?403:200);if(role!=='staff'){assert.equal((await h.get({employeeId:h.actor})).status,role==='manager'?404:200);const r=await h.api.GET(h.request('/api/management/time-reports',{headers:{'x-anaai-business-id':h.other}}));assert.equal(r.status,403);}});
test('Reports normal paid/meal shifts agree with Timesheets and CSV from the SAME result',async t=>{const h=await setup(t);await h.event('CLOCK_IN','2026-03-03T09:00:00Z');await h.event('BREAK_START','2026-03-03T10:00:00Z','PAID');await h.event('BREAK_END','2026-03-03T10:15:00Z','PAID');await h.event('BREAK_START','2026-03-03T12:00:00Z','MEAL');await h.event('BREAK_END','2026-03-03T12:30:00Z','MEAL');await h.event('CLOCK_OUT','2026-03-03T17:00:00Z');const r=await h.get();assert.equal(r.status,200);assert.equal(r.body.totals.workedMs,7.5*H);assert.equal(r.body.totals.paidBreakMs,H/4);assert.equal(r.body.totals.mealBreakMs,H/2);
 const sheet=await h.load('server/handlers/timesheets.ts').GET(h.request(`/api/management/timesheets/${h.target}?weekStart=2026-03-02`));assert.equal((await sheet.json()).totals.workedMs,r.body.totals.workedMs);
 const out=await h.exportCsv();assert.equal(out.status,200);assert.equal(out.body.csv,h.reports.reportCsv(out.body.report));assert.equal(out.body.report.totals.workedMs,r.body.totals.workedMs);const daily=csvRecords(out.body.csv)[0];assert.equal(daily.Worked,'7:30:00.000');assert.equal(daily['Paid Break'],'0:15:00.000');assert.equal(daily['Meal Break'],'0:30:00.000');const audit=(await h.db.query("select after_value from public.employee_management_actions where action='report.exported'")).rows[0].after_value;assert.equal(audit.row_count,1);assert.equal(Date.parse(audit.generated_at),Date.parse(out.body.report.generatedAt));assert.equal(audit.employee_filter,h.target);assert.equal(audit.csv,undefined);
});
for(const [label,timezone,start,end,date,expected]of [['overnight carry-in/out','UTC','2026-03-02T23:00:00Z','2026-03-04T01:00:00Z','2026-03-03',24],['spring DST','America/New_York','2026-03-08T05:00:00Z','2026-03-09T04:00:00Z','2026-03-08',23],['fall DST','America/New_York','2025-11-02T04:00:00Z','2025-11-03T05:00:00Z','2025-11-02',25]])test(`Reports ${label} clips local boundaries after loading carry-in`,async t=>{const h=await setup(t);await h.db.query('update public.businesses set timezone=$1 where id=$2',[timezone,h.business]);await h.event('CLOCK_IN',start);await h.event('CLOCK_OUT',end);const r=await h.get({startDate:date,endDate:date});assert.equal(r.status,200);assert.equal(r.body.totals.workedMs,expected*H);assert.equal(r.body.rows[0].workedMs,expected*H);});
test('Reports week crossover groupings and team totals use the same M05 calculation',async t=>{const h=await setup(t);await h.event('CLOCK_IN','2026-03-08T23:00:00Z');await h.event('CLOCK_OUT','2026-03-09T02:00:00Z');for(const grouping of ['employee','day','week','team']){const r=await h.get({startDate:'2026-03-08',endDate:'2026-03-09',grouping});assert.equal(r.status,200);assert.equal(r.body.totals.workedMs,3*H);assert.equal(r.body.rows.reduce((a,b)=>a+b.workedMs,0),3*H);if(grouping==='week')assert.deepEqual(r.body.rows.map(r=>r.week),['2026-03-02','2026-03-09']);}});
test('Reports correction crossing date boundary is interpreted BEFORE clipping',async t=>{const h=await setup(t);await h.event('CLOCK_IN','2026-03-03T23:00:00Z');const out=await h.event('CLOCK_OUT','2026-03-04T02:00:00Z');assert.equal((await h.get({startDate:'2026-03-04',endDate:'2026-03-04'})).body.totals.workedMs,2*H);await h.correct([{op:'REPLACE',target:out.id,occurredAt:'2026-03-03T23:30:00Z'}]);const r=await h.get({startDate:'2026-03-04',endDate:'2026-03-04'});assert.equal(r.body.totals.workedMs,0);assert.equal(r.body.totals.corrected,true);});
test('Report retry discards old dataset after a real correction, including CSV',async t=>{const h=await setup(t);await h.event('CLOCK_IN','2026-03-03T09:00:00Z');const out=await h.event('CLOCK_OUT','2026-03-03T10:00:00Z');const rpc=h.service.rpc;let changed=false,reads=0;h.service.rpc=async(name,args)=>{const r=await rpc(name,args);if(name==='m06_report_dataset'){reads++;if(!changed){changed=true;await h.correct([{op:'REPLACE',target:out.id,occurredAt:'2026-03-03T10:30:00Z'}]);}}return r;};const r=await h.exportCsv();assert.equal(r.status,200);assert.equal(reads,2);assert.equal(r.body.report.totals.workedMs,1.5*H);assert.equal(r.body.csv,h.reports.reportCsv(r.body.report));});
test('Report retries real CLOCK_OUT append and retains one common snapshot for open intervals',async t=>{const h=await setup(t);await h.event('CLOCK_IN','2026-03-03T09:00:00Z');const rpc=h.service.rpc;let changed=false;h.service.rpc=async(name,args)=>{const r=await rpc(name,args);if(name==='m06_report_dataset'&&!changed){changed=true;await as(h.db,'service_role',"select public.m05_record_time_event($1,$2,$3,$4,'CLOCK_OUT',null,$5)",[h.business,h.target,h.device,h.targetSession.id,uuid()]);}return r;};const r=await h.get();assert.equal(r.status,200);assert.equal(r.body.totals.open,false);assert.equal(r.body.rows[0].open,false);assert.equal(r.body.totals.workedMs,15*H);
});
test('Open reports use one snapshot for all employees and constant RPC count',async t=>{const h=await setup(t),now=Date.now(),stamp=new Date(now-H).toISOString();await h.event('CLOCK_IN',stamp);const second=await h.employee(); await h.db.query("insert into public.employee_time_events(business_id,employee_id,device_id,event_type,occurred_at,request_id) values($1,$2,$3,'CLOCK_IN',$4,$5)",[h.business,second,h.device,stamp,uuid()]);
 const calls=[],rpc=h.service.rpc;h.service.rpc=async(n,a)=>{calls.push(n);return rpc(n,a);};const today=new Date().toISOString().slice(0,10);const r=await h.get({startDate:today,endDate:today,employeeId:undefined,grouping:'employee'}); // URL builder omits undefined below
 assert.equal(r.status,200);const rows=r.body.rows.filter(r=>[h.target,second].includes(r.employeeId));assert.equal(rows[0].workedMs,rows[1].workedMs);assert.equal(calls.filter(n=>n==='m06_report_dataset').length,1);assert.equal(calls.filter(n=>n==='m06_ledger_read_versions').length,2);
});
test('Repeated report instability returns TIME_LEDGER_CHANGED without CSV or audit',async t=>{const h=await setup(t);await h.event('CLOCK_IN','2026-03-03T09:00:00Z');const out=await h.event('CLOCK_OUT','2026-03-03T10:00:00Z');let changes=0;const rpc=h.service.rpc;h.service.rpc=async(n,a)=>{const r=await rpc(n,a);if(n==='m06_report_dataset'){changes++;await h.correct([{op:'REPLACE',target:out.id,occurredAt:new Date(Date.parse(out.occurred_at)+changes*1000).toISOString()}]);}return r;};const r=await h.exportCsv();assert.equal(r.status,503);assert.equal(r.body.code,'TIME_LEDGER_CHANGED');assert.equal(changes,2);assert.equal(r.body.csv,undefined);assert.equal((await h.db.query("select count(*)::int n from public.employee_management_actions where action='report.exported'")).rows[0].n,0);});
for(const change of ['actor demotion','target promotion','session revoke','device revoke'])test(`Export ${change} after generation prevents CSV release`,async t=>{const h=await setup(t);await h.db.query("update public.business_members set role='manager'");const rpc=h.service.rpc;h.service.rpc=async(n,a)=>{if(n==='m06_record_time_export'){if(change==='actor demotion')await h.db.query("update public.business_members set role='staff'");if(change==='target promotion')await h.db.query("update public.employees set role='manager' where id=$1",[h.target]);if(change==='session revoke')await h.db.query('update public.employee_sessions set revoked_at=now() where id=$1',[h.session]);if(change==='device revoke')await h.db.query('update public.zude_devices set revoked_at=now() where id=$1',[h.device]);}return rpc(n,a);};const r=await h.exportCsv({},true);assert.ok([401,403].includes(r.status));assert.equal(r.body.csv,undefined);assert.equal((await h.db.query("select count(*)::int n from public.employee_management_actions where action='report.exported'")).rows[0].n,0);});
test('Report range validation, 93-day bound, browser RPC permissions and no silent event truncation',async t=>{const h=await setup(t);for(const extra of [{startDate:'2026-02-30'},{startDate:'2026-03-04'},{startDate:'2026-01-01',endDate:'2026-04-04'},{grouping:'payroll'},{employeeId:'invalid'},{endDate:'2999-01-01'}])assert.equal((await h.get(extra)).status,400);assert.equal((await h.get({startDate:'2026-01-01',endDate:'2026-04-03'})).status,200);
 for(const role of ['anon','authenticated'])await assert.rejects(as(h.db,role,"select public.m06_report_dataset($1,'owner',null,now()-interval '1 day',now())",[h.business]),e=>e.code==='42501');
 await h.db.query("insert into public.employee_time_events(business_id,employee_id,device_id,event_type,occurred_at,request_id) select $1,$2,$3,case when n%2=1 then 'CLOCK_IN' else 'CLOCK_OUT' end,'2026-03-03T00:00:00Z'::timestamptz+n*interval '1 second',gen_random_uuid() from generate_series(1,10002)n",[h.business,h.target,h.device]);const r=await h.get();assert.equal(r.status,503);assert.equal(r.body.code,'REPORT_LIMIT_EXCEEDED');assert.equal(r.body.rows,undefined);
});
test('CSV escapes commas/quotes/newlines and guards formula prefixes; bounds fail explicitly',async t=>{const h=await setup(t);for(const text of ['=SUM(A1:A2)','+formula','-formula','@formula','  =formula','\tvalue','\rvalue','\nvalue'])assert.ok(h.reports.csvCell(text).startsWith('"\''));assert.equal(h.reports.csvCell('A,"B"\nC'),'"A,""B""\nC"');const r=(await h.get()).body;const row={...r.rows[0],date:r.range.startDate};assert.throws(()=>h.reports.reportCsv({...r,dailyRows:Array(20001).fill(row)}),e=>e.code==='REPORT_LIMIT_EXCEEDED');assert.throws(()=>h.reports.reportCsv({...r,dailyRows:Array(18000).fill({...row,employee:'界'.repeat(100)})}),e=>e.code==='REPORT_LIMIT_EXCEEDED');});
test('Export audit failure returns no CSV and persists no partial audit',async t=>{const h=await setup(t);await h.db.exec("create function public.test_export_failure() returns trigger language plpgsql as $$begin raise exception 'synthetic'; end$$; create trigger test_export_failure before insert on public.employee_management_actions for each row execute function public.test_export_failure()");const r=await h.exportCsv();assert.equal(r.status,503);assert.equal(r.body.csv,undefined);assert.equal((await h.db.query('select count(*)::int n from public.employee_management_actions')).rows[0].n,0);});
test('Export audit history scopes employee and team metadata without storing CSV',async t=>{const h=await setup(t);assert.equal((await h.exportCsv()).status,200);assert.equal((await h.exportCsv({employeeId:undefined})).status,200);await h.db.query("update public.business_members set role='manager'");assert.equal((await h.exportCsv({employeeId:undefined})).status,200);const api=h.load('server/handlers/audit.ts');const read=async()=>{const r=await api.GET(h.request('/api/management/audit?category=reports'));assert.equal(r.status,200);return (await r.json()).entries;};let entries=await read();assert.equal(entries.length,2);assert.equal(entries.filter(e=>e.employee_id===null).length,1);assert.ok(entries.every(e=>e.action==='report.exported'));assert.ok(entries.every(e=>!Object.hasOwn(e.after_value,'csv')));await h.db.query("update public.employees set role='manager' where id=$1",[h.target]);entries=await read();assert.equal(entries.length,1);assert.equal(entries[0].employee_id,null);await h.db.query("update public.business_members set role='owner'");assert.equal((await read()).length,3);});

// Export detail is independent of the grouped screen, with one protected read.
const csvRecords = text => {
 const lines=text.trimEnd().split('\r\n').map(line=>line.slice(1,-1).split('","').map(cell=>cell.replaceAll('""','"')));
 return lines.slice(1).map(cells=>Object.fromEntries(lines[0].map((key,i)=>[key,cells[i]])));
};
for(const grouping of ['employee','day','week','team'])test(`Daily CSV ${grouping} screen: inclusive business-local range, carry-in/out and daily export audit`,async t=>{
 const h=await setup(t);await h.db.query("update public.businesses set timezone='America/Los_Angeles' where id=$1",[h.business]);
 await h.event('CLOCK_IN','2026-08-31T23:00:00-07:00');await h.event('CLOCK_OUT','2026-09-01T02:00:00-07:00');
 await h.event('CLOCK_IN','2026-10-01T23:00:00-07:00');await h.event('CLOCK_OUT','2026-10-02T02:00:00-07:00');
 const calls=[],rpc=h.service.rpc;h.service.rpc=async(n,a)=>{calls.push({n,a});return rpc(n,a);};
 const r=await h.exportCsv({startDate:'2026-09-01',endDate:'2026-10-01',grouping});assert.equal(r.status,200);
 assert.equal(r.body.report.grouping,grouping);const records=csvRecords(r.body.csv);
 assert.equal(records.length,31);assert.equal(new Set(records.map(r=>r.Date)).size,31);
 assert.ok(records.every(r=>r.Date>='2026-09-01'&&r.Date<='2026-10-01'));
 assert.equal(records[0].Date,'2026-09-01');assert.equal(records.at(-1).Date,'2026-10-01');
 assert.equal(Number(records[0]['Worked Milliseconds']),2*H);assert.equal(Number(records.at(-1)['Worked Milliseconds']),H);
 assert.equal(records.reduce((n,r)=>n+Number(r['Worked Milliseconds']),0),r.body.report.totals.workedMs);
 assert.ok(records.every(r=>r.Status==='Complete'&&r['Correction History']==='No'&&r.Timezone==='America/Los_Angeles'));
 assert.equal(records[0].Worked,'2:00:00.000');assert.doesNotMatch(r.body.csv,/employeeId|auditId|correctionId|local_week/);
 assert.equal(calls.filter(c=>c.n==='m06_report_dataset').length,1);assert.equal(calls.filter(c=>c.n==='m06_ledger_read_versions').length,2);
 const audit=calls.find(c=>c.n==='m06_record_time_export').a;assert.equal(audit.p_grouping,'day');assert.equal(audit.p_row_count,31);
 if(grouping==='employee'||grouping==='team')assert.equal(r.body.report.rows.length,1);
 const get=await h.get({startDate:'2026-09-01',endDate:'2026-10-01',grouping});assert.equal(get.body.dailyRows,undefined,'ordinary screen response does not carry extra CSV detail');
});
test('Daily CSV reflects corrections with existing lifetime history semantics',async t=>{
 const h=await setup(t);await h.event('CLOCK_IN','2026-03-03T23:00:00Z');const out=await h.event('CLOCK_OUT','2026-03-04T02:00:00Z');
 await h.correct([{op:'REPLACE',target:out.id,occurredAt:'2026-03-04T00:30:00Z'}]);
 const r=await h.exportCsv({endDate:'2026-03-04',grouping:'employee'});assert.equal(r.status,200);const rows=csvRecords(r.body.csv);
 assert.deepEqual(rows.map(r=>Number(r['Worked Milliseconds'])),[H,H/2]);assert.ok(rows.every(r=>r['Correction History']==='Yes'));
 assert.equal(r.body.report.rows.length,1);assert.equal(rows.length,2);assert.equal(r.body.report.totals.workedMs,1.5*H);
});
for(const [label,tz,date,start,end,hours]of [['spring','America/New_York','2026-03-08','2026-03-08T05:00:00Z','2026-03-09T04:00:00Z',23],['fall','America/New_York','2025-11-02','2025-11-02T04:00:00Z','2025-11-03T05:00:00Z',25]])test(`Daily CSV preserves ${label} DST allocation`,async t=>{
 const h=await setup(t);await h.db.query('update public.businesses set timezone=$1 where id=$2',[tz,h.business]);await h.event('CLOCK_IN',start);await h.event('CLOCK_OUT',end);
 const r=await h.exportCsv({startDate:date,endDate:date,grouping:'team'});assert.equal(r.status,200);const rows=csvRecords(r.body.csv);
 assert.equal(rows.length,1);assert.equal(rows[0].Date,date);assert.equal(Number(rows[0]['Worked Milliseconds']),hours*H);
});
test('Daily CSV open employees share one snapshot, preserve breaks, formula protection and authorization',async t=>{
 const h=await setup(t),now=Date.now(),start=new Date(now-H).toISOString(),today=new Date(now).toISOString().slice(0,10);
 await h.db.query("update public.employees set display_name='=formula' where id=$1",[h.target]);await h.event('CLOCK_IN',start);
 const second=await h.employee({name:'Second'});await h.db.query("insert into public.employee_time_events(business_id,employee_id,device_id,event_type,occurred_at,request_id) values($1,$2,$3,'CLOCK_IN',$4,$5)",[h.business,second,h.device,start,uuid()]);
 const r=await h.exportCsv({startDate:today,endDate:today,employeeId:undefined,grouping:'employee'});assert.equal(r.status,200);
 const rows=csvRecords(r.body.csv).filter(r=>["'=formula",'Second'].includes(r.Employee));assert.equal(rows.length,2);assert.equal(rows[0]['Worked Milliseconds'],rows[1]['Worked Milliseconds']);assert.ok(rows.every(r=>r.Status==='Open'));
 assert.equal(Number(rows[0]['Worked Milliseconds']),Math.min(Date.parse(r.body.report.snapshotAt),Date.parse(today+'T00:00:00Z')+24*H)-Math.max(Date.parse(start),Date.parse(today+'T00:00:00Z')));
 await h.db.query("update public.business_members set role='staff'");assert.equal((await h.exportCsv()).status,403);
 await h.db.query("update public.business_members set role='manager'");assert.equal((await h.exportCsv({employeeId:h.actor})).status,404);
 const foreign=await h.employee({tenant:h.other});assert.equal((await h.exportCsv({employeeId:foreign})).status,404);
 const denied=await h.api.EXPORT(new Request('https://zude.test/api/management/time-reports/export',{method:'POST',headers:{Authorization:'Bearer synthetic-account','x-zude-device':h.deviceCredential,'x-zude-employee-session':h.targetSession.value},body:JSON.stringify(h.input)}));assert.equal(denied.status,403);
});
