const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const {fixture}=require('./support/working-fixture.cjs');const {as}=require('./support/pglite-db.cjs');
async function setup(t){const h=await fixture(t),target=await h.employee(),handler=h.load('server/handlers/audit.ts');const get=async(query='',options={})=>{const r=await handler.GET(h.request('/api/management/audit'+query,options));return {status:r.status,body:await r.json()};};
 const edit=async(values,shared=false)=>{const stamp=(await h.db.query('select updated_at from public.employees where id=$1',[target])).rows[0].updated_at;return as(h.db,'service_role','select public.m04_write_employee($1,$2,$3,$4,null,$5::jsonb,$6,$7,$8,$9,$10)',[h.business,h.account,target,stamp,JSON.stringify(values),shared?'shared-device':'account','owner',shared?h.actor:null,shared?h.device:null,shared?h.session:null]);};
 return {...h,target,get,edit};}
test('Audit reads real Team actions, role changes, shared actor attribution and honest account-only attribution',async t=>{const h=await setup(t);await h.edit({display_name:'Edited employee'},true);await h.edit({role:'manager'});const r=await h.get();assert.equal(r.status,200);assert.equal(r.body.entries.length,2);assert.equal(r.body.entries[0].action,'employee.role_changed');assert.equal(r.body.entries[0].actor.name,null);assert.equal(r.body.entries[0].actor.userId,h.account);assert.equal(r.body.entries[1].actor.employeeId,h.actor);assert.equal(r.body.entries[1].actor.name,'Manager');assert.equal(r.body.entries[1].actor.mode,'shared-device');assert.doesNotMatch(JSON.stringify(r.body),/pin_hash|pin_salt|token_hash|actor_session_id|credential/);});
for(const role of ['staff','manager','owner'])test(`Audit ${role} authority`,async t=>{const h=await setup(t);await h.edit({display_name:'Edited'});await h.db.query('update public.business_members set role=$1',[role]);const r=await h.get();assert.equal(r.status,role==='staff'?403:200);if(role==='manager'){await h.db.query("update public.employees set role='manager' where id=$1",[h.target]);assert.equal((await h.get()).body.entries.length,0);}});
test('Audit filters authorized targets before cursor pagination and tenant isolation',async t=>{const h=await setup(t);await h.edit({display_name:'Visible'});await h.db.query("insert into public.employee_management_actions(business_id,subject_employee_id,actor_user_id,authority_mode,account_role,effective_role,action,after_value) select $1,$2,$3,'account','owner','owner','employee.created','{}'::jsonb from generate_series(1,55)",[h.business,h.actor,h.account]);await h.db.query("update public.business_members set role='manager'");const r=await h.get();assert.equal(r.body.entries.length,1);assert.equal(r.body.nextCursor,null);await h.db.query("update public.business_members set role='owner'");const a=await h.get();assert.equal(a.body.entries.length,50);const b=await h.get('?cursor='+a.body.nextCursor);assert.equal(b.body.entries.length,6);assert.equal(new Set([...a.body.entries,...b.body.entries].map(e=>e.id)).size,56);assert.equal((await h.get('?employeeId='+h.target)).body.entries.length,1);assert.equal((await h.get('?category=time')).body.entries.length,0);assert.equal((await h.get('?action=employee.updated')).body.entries.length,1);assert.equal((await h.get('',{headers:{'x-anaai-business-id':h.other}})).status,403);});
test('Audit shows actual correction and issue resolution, with bounded safe metadata',async t=>{const h=await setup(t);const e=await h.event(h.target,'CLOCK_IN',Date.now()-3600000);const c=(await as(h.db,'service_role',"select public.m06_correct_employee_time($1,$2,$3,'account','owner',null,null,null,$4::jsonb,'Missed punch',$5,0,$6,true,null,null) r",[h.business,h.target,h.account,JSON.stringify([{op:'INSERT',type:'CLOCK_OUT',after:e.id,occurredAt:new Date(Date.now()-1800000).toISOString()}]),crypto.randomUUID(),e.seq])).rows[0].r;
 const s=await h.sessionFor(h.target);const i=(await as(h.db,'service_role',"select public.m05_report_time_issue($1,$2,$3,$4,$5,null,null,'Missed punch') r",[h.business,h.target,h.device,s.id,crypto.randomUUID()])).rows[0].r.issue.id;
 await as(h.db,'service_role',"select public.m06_resolve_time_issue($1,$2,$3,'account','owner',null,null,null,'Corrected with employee',$4,$5)",[h.business,i,h.account,c.correction_id,crypto.randomUUID()]);
 const r=await h.get('?category=time');assert.deepEqual(r.body.entries.map(e=>e.action),['time.issue_resolved','time.corrected']);assert.equal(r.body.entries[0].issue_id,i);assert.equal(r.body.entries[1].correction_id,c.correction_id);assert.equal(r.body.entries[0].reason,'Corrected with employee');
});
test('Audit rejects invalid/unbounded filters and browser RPC access',async t=>{const h=await setup(t);for(const q of ['?startDate=2020-01-01&endDate=2026-01-01','?startDate=2026-02-30','?action=unknown','?category=unknown','?cursor=bad','?employeeId=bad','?employeeId=x&employeeId=y','?token=anything'])assert.equal((await h.get(q)).status,400);for(const role of ['anon','authenticated'])await assert.rejects(as(h.db,role,"select public.m06_audit_page($1,'owner',null,null,null,now()-interval '1 day',now(),null,null)",[h.business]),e=>e.code==='42501');await h.db.query('update public.employee_sessions set revoked_at=now() where id=$1',[h.session]);assert.equal((await h.get('',{shared:true})).status,401);});
