const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const {fixture}=require('./support/working-fixture.cjs');const {as}=require('./support/pglite-db.cjs');
const uuid=()=>crypto.randomUUID();
async function setup(t){const h=await fixture(t),handler=h.load('server/handlers/time-issues.ts'),target=await h.employee(),session=await h.sessionFor(target);
 const issue=async(employee=target,eventId=null)=>{const s=employee===target?session:await h.sessionFor(employee);return (await as(h.db,'service_role',"select public.m05_report_time_issue($1,$2,$3,$4,$5,'2026-03-03',$6,'Missed clock out') as r",[h.business,employee,h.device,s.id,uuid(),eventId])).rows[0].r.issue.id;};
 const id=await issue();const json=async r=>({status:r.status,body:await r.json()});
 const get=(path='/api/management/time-issues',shared=false)=>handler[path.startsWith('/api/management/time-issues/')?'DETAIL':'GET'](h.request(path,{shared})).then(json);
 const resolve=(body={note:'Reviewed with employee'},key=uuid(),shared=false,issueId=id)=>handler.RESOLVE(new Request(`https://zude.test/api/management/time-issues/${issueId}/resolve`,{method:'POST',headers:{Authorization:'Bearer synthetic-account',...(shared?{'x-zude-device':h.deviceCredential,'x-zude-employee-session':h.sessionCredential}:{}),'Idempotency-Key':key},body:JSON.stringify(body)})).then(json);
 const counts=async()=> (await h.db.query("select (select count(*)::int from public.employee_time_issue_resolutions) resolutions,(select count(*)::int from public.employee_management_actions where action='time.issue_resolved') audits")).rows[0];
 return {...h,handler,target,id,issue,get,resolve,counts};}
for(const role of ['staff','manager','owner'])test(`Issues ${role} authority and target filtering before page`,async t=>{const h=await setup(t);await h.issue(h.actor);await h.db.query('update public.business_members set role=$1',[role]);const r=await h.get();assert.equal(r.status,role==='staff'?403:200);if(role!=='staff')assert.equal(r.body.issues.length,role==='manager'?1:2);});
test('Issue detail retains original report and uses protected Timesheet context',async t=>{const h=await setup(t);const r=await h.get(`/api/management/time-issues/${h.id}`);assert.equal(r.status,200);assert.equal(r.body.issue.note,'Missed clock out');assert.equal(r.body.timesheet.week.startDate,'2026-03-02');assert.equal(r.body.timesheet.totals.workedMs,0);assert.equal(JSON.stringify(r.body).includes('token_hash'),false);});
test('Resolution is final, audited, immutable and idempotent; original note retained',async t=>{const h=await setup(t),key=uuid();assert.equal((await h.resolve(undefined,key)).status,201);assert.equal((await h.resolve(undefined,key)).status,200);assert.equal((await h.resolve({note:'Different resolution'},key)).body.code,'TIME_REQUEST_CONFLICT');assert.equal((await h.resolve()).body.code,'ISSUE_ALREADY_RESOLVED');assert.deepEqual(await h.counts(),{resolutions:1,audits:1});const r=await h.get(`/api/management/time-issues/${h.id}`);assert.equal(r.body.issue.note,'Missed clock out');assert.equal(r.body.issue.resolution.note,'Reviewed with employee');
 await h.db.exec('grant update,delete,truncate on public.employee_time_issues,public.employee_time_issue_resolutions to service_role');
 for(const sql of ["update public.employee_time_issues set note='Tampered'","delete from public.employee_time_issues","truncate public.employee_time_issues cascade","update public.employee_time_issue_resolutions set note='Tampered'","delete from public.employee_time_issue_resolutions","truncate public.employee_time_issue_resolutions cascade"])await assert.rejects(as(h.db,'service_role',sql),e=>e.code==='42501');
 assert.deepEqual(await h.counts(),{resolutions:1,audits:1});});
for(const change of ['actor demotion','target promotion','session revoke','device revoke','employee generation','device generation'])test(`Resolution revalidates ${change} transactionally`,async t=>{const h=await setup(t);await h.db.query("update public.business_members set role='manager'");const rpc=h.service.rpc;h.service.rpc=async(name,args)=>{if(name==='m06_resolve_time_issue'){
 if(change==='actor demotion')await h.db.query("update public.business_members set role='staff'");
 if(change==='target promotion')await h.db.query("update public.employees set role='manager' where id=$1",[h.target]);
 if(change==='session revoke')await h.db.query('update public.employee_sessions set revoked_at=now() where id=$1',[h.session]);
 if(change==='device revoke')await h.db.query('update public.zude_devices set revoked_at=now() where id=$1',[h.device]);
 if(change==='employee generation')await h.db.query('update public.employees set updated_at=now() where id=$1',[h.actor]);
 if(change==='device generation')await h.db.query('update public.zude_devices set updated_at=now() where id=$1',[h.device]);
 }return rpc(name,args);};const r=await h.resolve(undefined,uuid(),true);assert.ok([401,403].includes(r.status));assert.deepEqual(await h.counts(),{resolutions:0,audits:0});});
test('Tenant, shared employee authority and malformed resolution fail closed',async t=>{const h=await setup(t);assert.equal((await h.resolve(undefined,uuid(),false,uuid())).status,404);await h.db.query("update public.employees set role='employee' where id=$1",[h.actor]);assert.equal((await h.resolve(undefined,uuid(),true)).status,403);for(const note of ['','  ','!!','...'])assert.equal((await h.resolve({note})).status,400);assert.deepEqual(await h.counts(),{resolutions:0,audits:0});});
test('Resolution audit and compatibility projection roll back together',async t=>{const h=await setup(t);await h.db.exec("create function public.test_resolution_failure() returns trigger language plpgsql as $$ begin raise exception 'synthetic failure'; end $$; create trigger test_resolution_failure before insert on public.employee_time_issue_resolutions for each row execute function public.test_resolution_failure()");assert.equal((await h.resolve()).status,503);assert.deepEqual(await h.counts(),{resolutions:0,audits:0});assert.equal((await h.get()).body.issues[0].status,'open');});
test('Correction linkage is same-employee committed history; correction never auto-resolves',async t=>{const h=await setup(t),at='2026-03-03T09:00:00Z';const first=await h.event(h.target,'CLOCK_IN',Date.parse(at));const c=(await as(h.db,'service_role',"select public.m06_correct_employee_time($1,$2,$3,'account','owner',null,null,null,$4::jsonb,'Missed punch',$5,0,$6,true,null,null) r",[h.business,h.target,h.account,JSON.stringify([{op:'INSERT',type:'CLOCK_OUT',after:first.id,occurredAt:'2026-03-03T10:00:00Z'}]),uuid(),first.seq])).rows[0].r;
 assert.equal((await h.get()).body.issues[0].status,'open');assert.equal((await h.resolve({note:'Reviewed correction',correctionId:uuid()})).status,400);
 const other=await h.issue(h.actor);assert.equal((await h.resolve({note:'Reviewed correction',correctionId:c.correction_id},uuid(),false,other)).status,400);
 assert.equal((await h.resolve({note:'Reviewed correction',correctionId:c.correction_id})).status,201);
 assert.equal((await h.get(`/api/management/time-issues/${h.id}`)).body.issue.resolution.correctionId,c.correction_id);
});
test('Issue context propagates TIME_LEDGER_CHANGED and recovers on stable refresh',async t=>{const h=await setup(t),rpc=h.service.rpc;let n=0;h.service.rpc=async(name,args)=>{const r=await rpc(name,args);if(name==='m06_ledger_read_versions'&&r.data?.length)r.data[0].correctionRevision=String(++n);return r;};const r=await h.get(`/api/management/time-issues/${h.id}`);assert.equal(r.status,503);assert.equal(r.body.code,'TIME_LEDGER_CHANGED');h.service.rpc=rpc;assert.equal((await h.get(`/api/management/time-issues/${h.id}`)).status,200);});
test('Issue RPCs and original storage deny browser roles; foreign tenant detail hidden',async t=>{const h=await setup(t);for(const role of ['anon','authenticated'])await assert.rejects(as(h.db,role,'select public.m06_time_issues_page($1,\'owner\',null,null,null,null)',[h.business]),e=>e.code==='42501');const r=await h.handler.DETAIL(h.request(`/api/management/time-issues/${h.id}`,{headers:{'x-anaai-business-id':h.other}}));assert.equal(r.status,403);});

test('Corrected and voided referenced events retain original report provenance',async t=>{
 const h=await setup(t),first=await h.event(h.target,'CLOCK_IN',Date.parse('2026-03-03T09:00:00Z')),last=await h.event(h.target,'CLOCK_OUT',Date.parse('2026-03-03T10:00:00Z')),issue=await h.issue(h.target,first.id);
 const correct=async(ops,revision)=>as(h.db,'service_role',"select public.m06_correct_employee_time($1,$2,$3,'account','owner',null,null,null,$4::jsonb,'Reviewed report',$5,$6,$7,true,null,null)",[h.business,h.target,h.account,JSON.stringify(ops),uuid(),revision,last.seq]);
 await correct([{op:'REPLACE',target:first.id,occurredAt:'2026-03-03T09:15:00Z'}],0);
 let r=await h.get('/api/management/time-issues/'+issue);assert.equal(r.status,200);assert.equal(Date.parse(r.body.originalEvent.occurred_at),Date.parse(first.occurred_at));assert.equal(Date.parse(r.body.currentEvent.occurred_at),Date.parse('2026-03-03T09:15:00Z'));assert.equal(r.body.timesheet.totals.workedMs,45*60000);
 await correct([{op:'VOID',target:first.id},{op:'VOID',target:last.id}],1);
 r=await h.get('/api/management/time-issues/'+issue);assert.equal(r.status,200);assert.equal(r.body.referencedEventVoided,true);assert.equal(r.body.currentEvent,null);assert.equal(r.body.issue.time_event_id,first.id);assert.equal(r.body.issue.status,'open');assert.equal(r.body.timesheet.totals.workedMs,0);
});
test('Issue scope filtering precedes keyset pagination and duplicate resolution is atomic',async t=>{
 const h=await setup(t);await h.db.query("update public.business_members set role='manager'");
 const bulk=employee=>h.db.query("insert into public.employee_time_issues(business_id,employee_id,device_id,note,request_id) select $1,$2,$3,'Synthetic report',gen_random_uuid() from generate_series(1,55)",[h.business,employee,h.device]);
 await bulk(h.actor);assert.equal((await h.get()).body.issues.length,1);await bulk(h.target);
 const a=await h.get();assert.equal(a.body.issues.length,50);assert.ok(a.body.nextCursor);const b=await h.get('/api/management/time-issues?cursor='+a.body.nextCursor);assert.equal(b.body.issues.length,6);assert.equal(new Set([...a.body.issues,...b.body.issues].map(i=>i.id)).size,56);
 const key=uuid(),r=await Promise.all([h.resolve(undefined,key),h.resolve(undefined,key)]);assert.deepEqual(r.map(x=>x.status).sort(),[200,201]);assert.deepEqual(await h.counts(),{resolutions:1,audits:1});
});
test('Foreign-business committed correction cannot be linked to local issue; tenant cascade retained',async t=>{const h=await setup(t),foreign=uuid();await h.db.query("insert into public.employees(id,business_id,display_name,role,pin_hash,pin_salt) values($1,$2,'Foreign','employee','synthetic','synthetic')",[foreign,h.other]);await h.db.query("insert into public.business_members(business_id,user_id,role) values($1,$2,'owner')",[h.other,h.account]);const c=(await as(h.db,'service_role',"select public.m06_correct_employee_time($1,$2,$3,'account','owner',null,null,null,$4::jsonb,'Foreign synthetic correction',$5,0,0,true,null,null) r",[h.other,foreign,h.account,JSON.stringify([{op:'INSERT',type:'CLOCK_IN',atStart:true,occurredAt:'2026-03-03T09:00:00Z'}]),uuid()])).rows[0].r;assert.equal(c.ok,true);assert.equal((await h.resolve({note:'Attempted foreign link',correctionId:c.correction_id})).status,400);assert.deepEqual(await h.counts(),{resolutions:0,audits:0});assert.equal((await h.resolve()).status,201);await h.db.query('delete from public.businesses where id=$1',[h.business]);assert.deepEqual(await h.counts(),{resolutions:0,audits:0});});
