const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const ts=require('typescript');
function load(file,imports,globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('apps/zude-mobile/src/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,...globals,require(name){if(name in imports)return imports[name];throw Error(name)}});return exports;}
class ApiError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code;}}
function api(status=200,body={success:true},fail=false){const calls=[];const module=load('lib/employee-identity-api.ts',{'./api':{ZudeApiError:ApiError,apiUrl:p=>'https://zude.test'+p,apiWrite:(...args)=>{calls.push(args);return Promise.resolve({})}}},{fetch:async(url,options)=>{calls.push({url,options});if(fail)throw Error('private-provider-body');return {ok:status<400,status,json:async()=>body};}});return {...module,calls};}
test('device registration uses member transport with selected business and expected account',async()=>{const h=api();await h.registerDevice('iPad','business','account');assert.equal(h.calls[0][0],'/api/devices');assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0][1])),{name:'iPad'});assert.equal(h.calls[0][2].expectedUserId,'account');});
test('PIN transport uses device credential and no claimed tenant/employee authority',async()=>{const h=api();await h.identityRequest('/api/device/pin',{businessId:'business',credential:'synthetic-device'},{pin:'1234'});const request=h.calls[0];assert.equal(request.options.headers.Authorization,'ZudeDevice synthetic-device');assert.equal(request.options.headers['x-anaai-business-id'],undefined);assert.deepEqual(JSON.parse(request.options.body),{pin:'1234'});assert.equal(request.options.redirect,'error');assert.equal(request.options.cache,'no-store');});
for(const status of [401,429,503])test(`identity ${status} rejects provider text`,async()=>{const h=api(status,{success:false,error:'private-provider-body'});await assert.rejects(h.identityRequest('/api/employee-session/validate',{businessId:'b',credential:'synthetic-device'},{session:'synthetic-session'}),e=>e.status===status&&!e.message.includes('private-provider-body'));});
test('network failure has safe typed error',async()=>{const h=api(200,{},true);await assert.rejects(h.identityRequest('/api/device/pin',{businessId:'b',credential:'synthetic-device'},{pin:'1234'}),e=>e.code==='NETWORK_ERROR'&&!e.message.includes('private-provider-body'));});
function vault(platform='ios',fail=false){const calls=[];let value=null;const module=load('features/identity/device-vault.ts',{'react-native':{Platform:{OS:platform}},'expo-secure-store':{WHEN_UNLOCKED_THIS_DEVICE_ONLY:42,getItemAsync:async key=>{calls.push(['get',key]);if(fail)throw Error('storage');return value;},setItemAsync:async(key,raw,options)=>{calls.push(['set',key,options]);if(fail)throw Error('storage');value=raw;}}});return {...module,calls};}
test('native device persistence uses OS secure storage, device-bound accessibility',async()=>{const h=vault();const device={businessId:'b',credential:'synthetic-device'};await h.saveDevice(device);assert.equal(h.calls[0][2].keychainAccessible,42);assert.deepEqual(JSON.parse(JSON.stringify(await h.readDevice())),device);});
test('native storage failure never downgrades to plaintext storage',async()=>{const h=vault('ios',true);await assert.rejects(h.saveDevice({businessId:'b',credential:'synthetic-device'}));await assert.rejects(h.readDevice());});
test('web preview is volatile and never calls persistent storage',async()=>{const h=vault('web');await h.saveDevice({businessId:'b',credential:'synthetic-device'});assert.equal((await h.readDevice()).businessId,'b');assert.equal(h.calls.length,0);assert.equal(await vault('web').readDevice(),null);});

function screenHarness({device={businessId:'business',credential:'synthetic-device'},delayed=false}={}){
 const states=[],effects=[],calls=[];let cursor=0,ec=0,background,resolveLogin,context;
 const react={createContext:()=>({Provider:'Provider'}),useContext:()=>context,useState(initial){const i=cursor++;if(!(i in states))states[i]=typeof initial==='function'?initial():initial;return [states[i],v=>{states[i]=typeof v==='function'?v(states[i]):v}];},useRef(initial){const i=cursor++;if(!(i in states))states[i]={current:initial};return states[i];},useEffect(fn,deps){const i=ec++,old=effects[i];if(!old||deps.some((v,j)=>v!==old.deps[j]))effects[i]={fn,deps,pending:true,cleanup:old?.cleanup};}};
 react.useLayoutEffect = react.useEffect;
  react.useCallback = (fn, deps) => { const memo = react.useRef(null); if (!memo.current || deps.some((v, i) => !Object.is(v, memo.current.deps[i]))) memo.current = { fn, deps }; return memo.current.fn; };
 const jsx={jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};
 const result={success:true,session:'synthetic-session',expiresAt:new Date(Date.now()+3600000).toISOString(),employee:{id:'e',businessId:'business',name:'Employee',role:'employee'},permissions:[]};
 const imports={'./AuthorityDiagnostic':{AuthorityDiagnostic:'AuthorityDiagnostic'},react,'react/jsx-runtime':jsx,'react-native':{AppState:{addEventListener(_,fn){background=fn;return {remove(){}};}},Platform:{OS:'ios'},ScrollView:'ScrollView',Text:'Text',View:'View'},'../business/BusinessContext':{useBusiness:()=>({business:{id:'business',name:'Business',role:'owner'},userId:'account'})},'../../components/ui':{Button:'Button',styles:{}},'../../components/workspace':{Field:'Field',WorkspaceHeader:'Header',workspaceStyles:{}},'../../lib/api':{ZudeApiError:ApiError},'../../theme/tokens':{theme:{space:{xl:24,lg:16}}},'./device-vault':{readDevice:async()=>device,saveDevice:async()=>{},readSharedMode:async()=>!!device,markSharedMode:async()=>{},clearSharedMode:async()=>{},forgetDevice:async()=>{}},'../../lib/employee-identity-api':{identityRequest:async(path,device,body)=>{calls.push({path,body});if(path==='/api/device/pin')return delayed?new Promise(r=>resolveLogin=r):result;return {success:true};},registerDevice:async()=>({device:{business_id:'business'},credential:'synthetic-device'}),deviceCredentialRejected:()=>false,isDeviceRejectionCode:()=>false},
 // M04 shared-device modules: real implementations (no network).
 './EmployeeActivityContext':{EmployeeActivityContext:{Provider:'ActivityProvider'}}, './employee-inactivity':load('features/identity/employee-inactivity.ts',{},{Date,setTimeout:()=>2,clearTimeout(){}}),
 '../../lib/account-proof':load('lib/account-proof.ts',{},{Date}),'../../lib/account-session':{signOutAccount:async()=>{}},'../../lib/operational-identity':load('lib/operational-identity.ts',{'./api':{ZudeApiError:ApiError}})};
 const contextExports={};
 const compile=(file,exports)=>vm.runInNewContext(ts.transpileModule(fs.readFileSync('apps/zude-mobile/src/features/identity/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Date,__DEV__:false,setTimeout:()=>1,clearTimeout(){},require:n=>{if(n==='./EmployeeIdentityContext')return contextExports;if(n in imports)return imports[n];throw Error(n);}});
 compile('EmployeeIdentityContext.tsx',contextExports);
 const exports={};compile('DeviceIdentityScreen.tsx',exports);
 function nodes(n){if(!n||typeof n!=='object')return [];if(Array.isArray(n))return n.flatMap(nodes);return [n,...nodes(n.props?.children)];}
 let tree;const h={calls,render(){cursor=0;ec=0;context=contextExports.EmployeeIdentityProvider({children:null}).props.value;tree=exports.DeviceIdentityScreen();for(const e of effects)if(e.pending){e.cleanup?.();e.cleanup=e.fn();e.pending=false;}return tree;},click(label){const n=nodes(tree).find(n=>n.type==='Button'&&n.props.label===label);assert.ok(n,'Button '+label);assert.ok(!n.props.disabled,'Enabled '+label);n.props.onPress();},background(){background('background');},finishLogin(){resolveLogin(result);},unmount(){for(const e of effects)e.cleanup?.();},hasText(value){return JSON.stringify(tree).includes(value);}};return h;
}
const flush=()=>new Promise(r=>setImmediate(r));
async function enter(h){h.render();await flush();h.render();for(const digit of ['1','2','3','4']){h.click(digit);h.render();}h.click('Unlock');await flush();h.render();}
test('native background lock revokes employee session and keeps device credential out of storage writes',async()=>{const h=screenHarness();await enter(h);assert.ok(h.hasText('Employee'));h.background();await flush();h.render();assert.ok(h.calls.some(c=>c.path==='/api/employee-session/lock'));assert.ok(!h.hasText('Employee identity is active'));h.unmount();});
test('late PIN success after backgrounding is revoked rather than restoring identity',async()=>{const h=screenHarness({delayed:true});await enter(h);h.background();h.finishLogin();await flush();h.render();assert.ok(h.calls.some(c=>c.path==='/api/employee-session/lock'));assert.ok(!h.hasText('Employee identity is active'));h.unmount();});
test('late PIN success after leaving the authenticated workspace is revoked',async()=>{const h=screenHarness({delayed:true});await enter(h);h.unmount();h.finishLogin();await flush();assert.ok(h.calls.some(c=>c.path==='/api/employee-session/lock'));});
