const {test}=require('node:test');const assert=require('node:assert/strict');const {screen,load,ApiError}=require('./support/native-management.cjs');
const summaryRow={employeeId:'e',employee:'Visible employee',employeeRole:'employee',workedMs:3600000,paidBreakMs:0,mealBreakMs:0,activeWorkMs:3600000,finalPaidMs:3600000,open:false,corrected:false};
const report={summaryRows:[summaryRow],peopleWorked:1,provisionalPeople:0,exceptions:[],businessId:'b',timezone:'UTC',range:{startDate:'2026-03-01',endDate:'2026-03-03'},grouping:'employee',employeeFilter:null,snapshotAt:'2026-03-03T00:00:00Z',generatedAt:'2026-03-03T00:00:00Z',totals:{workedMs:3600000,paidBreakMs:0,mealBreakMs:0,open:false,corrected:false},rows:[{employeeId:'e',employee:'Visible employee',date:null,week:null,workedMs:3600000,paidBreakMs:0,mealBreakMs:0,open:false,corrected:false}]};
function setup(){const reads=[],exports=[],shares=[];const h=screen('features/management/ReportsScreen.tsx',{'../../lib/time-reports-api':{getReportDirectory:async()=>({employees:[]}),getTimeReport:(business,filters,signal)=>new Promise((resolve,reject)=>reads.push({business,filters,signal,resolve,reject})),exportTimeReport:(business,user,filters,signal,format)=>new Promise((resolve,reject)=>exports.push({business,user,filters,signal,format,resolve,reject})),reportMessage:()=> 'Safe report error'},'../../lib/timesheets-api':{getTimesheetDirectory:async()=>({employees:[]})},'./ReportDateField':{ReportDateField:'LabeledField'},'../../components/operations':{Action:'Button'},'../../theme/tokens':load('theme/tokens.ts'),'./reportPeriods':load('features/management/reportPeriods.ts'),'../../lib/share-time-report':{shareTimeReport:async(...args)=>shares.push(args)}});return {h,reads,exports,shares};}
test('Reports clamps pagination when an authority refresh returns fewer rows',async()=>{
 const {h,reads,exports}=setup();
 reads[0].resolve({...report,summaryRows:Array.from({length:101},(_,i)=>({...summaryRow,employeeId:`e-${i}`}))});await h.flush();
 h.click('Next rows');assert.match(h.text(),/51–100/);
 h.click('Export Report');h.click('Employee Hours Summary CSV');exports[0].reject(new ApiError(403,'ROLE_FORBIDDEN'));await h.flush();
 reads[1].resolve(report);await h.flush();
 assert.match(h.text(),/Visible employee/);
 assert.equal(h.button('Previous rows'),undefined);h.dispose();
});
test('Reports export replaces visible report with exact exported result and prevents duplicate submission',async()=>{const {h,reads,exports,shares}=setup();reads[0].resolve(report);await h.flush();h.click('Export Report');h.click('Employee Hours Summary CSV');assert.equal(h.button('Preparing report…').props.disabled,true);assert.equal(exports.length,1);assert.equal(exports[0].user,'u');assert.equal(exports[0].format,'summary-v1');const updated={...report,summaryRows:[{...summaryRow,workedMs:7200000,activeWorkMs:7200000,finalPaidMs:7200000}],totals:{...report.totals,workedMs:7200000}};exports[0].resolve({report:updated,csv:'exact server CSV',filename:'safe.csv'});await h.flush();assert.equal(shares[0][0],'exact server CSV');assert.match(h.text(),/7200000/);assert.match(h.text(),/Report prepared/);h.dispose();});
for(const change of ['lock','business','role','logout','background','blur'])test(`Reports ${change} aborts export, hides data and ignores late response`,async()=>{const {h,reads,exports,shares}=setup();reads[0].resolve(report);await h.flush();h.click('Export Report');h.click('Employee Hours Summary CSV');if(change==='lock')h.context.identity=null;if(change==='business')h.context.business={id:'other',name:'Other'};if(change==='role')h.context.managementRole='staff';if(change==='logout')h.context.userId=null;if(change==='background')h.background('background');if(change==='blur')h.focus(false);h.render();assert.equal(exports[0].signal.aborted,true);exports[0].resolve({report,csv:'private',filename:'safe.csv'});await h.flush();assert.equal(shares.length,0);assert.doesNotMatch(h.text(),/Visible employee/);h.dispose();});
test('Reports filter changes ignore stale reads; export failure cannot invoke sharing',async()=>{const {h,reads,exports,shares}=setup();h.click('Choose dates');h.field('Start date (YYYY-MM-DD)','2026-03-01');h.field('End date (YYYY-MM-DD)','2026-03-03');h.click('Apply dates');assert.equal(reads[0].signal.aborted,true);reads[0].resolve({...report,rows:[{...report.rows[0],employee:'Stale employee'}]});await h.flush();assert.doesNotMatch(h.text(),/Stale employee/);reads[1].resolve(report);await h.flush();h.click('Export Report');h.click('Employee Hours Summary CSV');exports[0].reject(new ApiError(503,'TIME_LEDGER_CHANGED'));await h.flush();assert.equal(shares.length,0);assert.match(h.text(),/Safe report error/);h.dispose();});
test('Report API validates tenant and filename and binds export to expected account',async()=>{let options,response={businessId:'b',report,csv:'CSV',filename:'zude-time-2026-03-01-2026-03-03.csv',auditId:'audit'};const api=load('lib/time-reports-api.ts',{'./api':{ZudeApiError:ApiError,apiWrite:async(_,body,o)=>{options=o;return response;},apiGet:async()=>report},'./operational-identity':{operationalRequest:(_,send)=>send({'x-zude-device':'synthetic'})}});await api.exportTimeReport('b','u',{},new AbortController().signal);assert.equal(options.expectedUserId,'u');assert.equal(options.method,'POST');assert.equal(options.headers['x-zude-device'],'synthetic');response={...response,filename:'../../private.csv'};await assert.rejects(api.exportTimeReport('b','u',{},new AbortController().signal));await assert.rejects(api.getTimeReport('other',{},new AbortController().signal));});
for(const failure of [false,true])test(`Native private CSV cache is removed after share ${failure?'failure':'success'}`,async()=>{const files=[],shared=[];class File{constructor(_,name){this.uri='file://private/'+name;this.exists=false;files.push(this);}create(){this.exists=true;}write(v){this.value=v;}delete(){this.exists=false;}}class Directory{create(){}list(){return [];}}const api=load('lib/share-time-report.ts',{'expo-file-system':{File,Directory,Paths:{cache:'private'}},'expo-sharing':{isAvailableAsync:async()=>true,shareAsync:async(uri,options)=>{shared.push({uri,options});assert.equal(files[0].exists,true);if(failure)throw Error('share failed');}},'expo-crypto':{randomUUID:()=> 'unique'},'./api':{ZudeApiError:ApiError}});const promise=api.shareTimeReport('exact CSV','report.csv',new AbortController().signal);if(failure)await assert.rejects(promise);else await promise;assert.equal(files[0].value,'exact CSV');assert.equal(files[0].exists,false);assert.equal(shared[0].options.mimeType,'text/csv');});
test('Native sharing cancels before file creation and fails safely if unavailable',async()=>{let created=0;class File{constructor(){created++;}}const api=load('lib/share-time-report.ts',{'expo-file-system':{File,Directory:class{},Paths:{}},'expo-sharing':{isAvailableAsync:async()=>false},'expo-crypto':{},'./api':{ZudeApiError:ApiError}});const c=new AbortController();c.abort();await assert.rejects(api.shareTimeReport('CSV','report.csv',c.signal),e=>e.code==='CANCELLED');await assert.rejects(api.shareTimeReport('CSV','report.csv',new AbortController().signal),e=>e.code==='SHARING_UNAVAILABLE');assert.equal(created,0);});
test('Reports explicit authority failure hides loaded data and refreshes authorized scope',async()=>{const {h,reads,exports}=setup();reads[0].resolve(report);await h.flush();h.click('Export Report');h.click('Employee Hours Summary CSV');exports[0].reject(new ApiError(403,'ROLE_FORBIDDEN'));await h.flush();assert.doesNotMatch(h.text(),/Visible employee/);assert.equal(reads.length,2);h.dispose();});
test('Web export uses and revokes a local Blob URL with no credential-bearing link',async()=>{const calls=[];const anchor={remove:()=>calls.push('remove'),click:()=>calls.push('click')};const api=load('lib/share-time-report.web.ts',{'./api':{ZudeApiError:ApiError}},{Blob,URL:{createObjectURL:blob=>{assert.equal(blob.size,3);return 'blob:local';},revokeObjectURL:url=>calls.push(url)},document:{createElement:()=>anchor,body:{appendChild:()=>{}}},setTimeout:fn=>fn()});await api.shareTimeReport('CSV','report.csv',new AbortController().signal);assert.equal(anchor.href,'blob:local');assert.equal(anchor.download,'report.csv');assert.deepEqual(calls,['click','remove','blob:local']);});
test('Daily CSV export preserves employee grouping in the validated mobile report',async()=>{
 const response={businessId:'b',report:{...report,dailyRows:[{...report.rows[0],date:'2026-03-01'},{...report.rows[0],date:'2026-03-02'}]},csv:'daily CSV',filename:'zude-time-2026-03-01-2026-03-03.csv',auditId:'audit'};
 const api=load('lib/time-reports-api.ts',{'./api':{ZudeApiError:ApiError,apiWrite:async()=>response},'./operational-identity':{operationalRequest:(_,send)=>send({})}});
 const result=await api.exportTimeReport('b','u',{grouping:'employee'},new AbortController().signal);
 assert.equal(result.report.grouping,'employee');assert.equal(result.report.rows.length,1);assert.equal(result.csv,'daily CSV');assert.equal(result.report.dailyRows,undefined);
});

test('REPORTS01B full-width table shows roles and paid totals without duplicate rows or legacy controls',async()=>{
 const {h,reads}=setup();reads[0].resolve({...report,summaryRows:[{...summaryRow,employee:'A very long employee name with several family names',employeeRole:'owner',open:true}],provisionalPeople:1});await h.flush();
 assert.match(h.text(),/Owner/);assert.match(h.text(),/Provisional/);assert.match(h.text(),/INCOMPLETE RECORDS/);assert.equal(h.nodes().filter(n=>n.type==='Text'&&n.props.children==='A very long employee name with several family names').length,1);
 assert.equal(h.nodes().some(n=>n.props.horizontal),false);assert.doesNotMatch(h.text(),/Report filters|Daily hours CSV|Legacy daily CSV|snapshot_at/);
 h.click('Export Report');assert.ok(h.button('Employee Hours Summary CSV'));assert.ok(h.button('Detailed Timesheet CSV'));h.dispose();
});
test('REPORTS01B technical details collapse and empty/error states do not fabricate totals',async()=>{
 const {h,reads}=setup();assert.match(h.text(),/Loading reports/);reads[0].resolve({...report,summaryRows:[],peopleWorked:0,rows:[],totals:{...report.totals,workedMs:0}});await h.flush();assert.match(h.text(),/No recorded work for this period/);assert.doesNotMatch(h.text(),/Snapshot:/);h.click('Report Details');assert.match(h.text(),/Snapshot:/);h.click('Report Details');assert.doesNotMatch(h.text(),/Snapshot:/);h.click('Refresh');reads[1].reject(new ApiError(503,'TIME_UNAVAILABLE'));await h.flush();assert.match(h.text(),/Report unavailable/);assert.doesNotMatch(h.text(),/FINAL PAID HOURS/);h.dispose();
});
test('REPORTS01B table pagination never becomes an export employee filter',async()=>{
 const {h,reads,exports}=setup();reads[0].resolve({...report,summaryRows:Array.from({length:120},(_,i)=>({...summaryRow,employeeId:`e${i}`,employee:`Person ${i}`}))});await h.flush();h.click('Next rows');assert.match(h.text(),/51–100/);h.click('Export Report');h.click('Detailed Timesheet CSV');assert.equal(JSON.stringify(exports[0].filters),'{}');assert.equal(exports[0].format,'shifts-v1');assert.equal(h.nodes().filter(n=>n.type==='Text'&&/^Person /.test(n.props.children)).length,50);h.dispose();
});

test('REPORTS01C unapplied and invalid date presets do not mislabel the displayed period',async()=>{
 const {h,reads}=setup();reads[0].resolve(report);await h.flush();h.click('2 Weeks');
 assert.equal(h.button('Custom').props.selected,true);assert.equal(h.button('2 Weeks').props.selected,false);assert.equal(reads.length,1);
 h.click('Apply dates');assert.match(h.text(),/Choose the first day/);assert.equal(h.button('Custom').props.selected,true);assert.equal(reads.length,1);
 h.field('Start date (YYYY-MM-DD)','2026-03-01');h.click('Apply dates');assert.equal(h.button('2 Weeks').props.selected,true);assert.equal(reads[1].filters.endDate,'2026-03-14');h.dispose();
});
test('REPORTS01C explicit statuses and no repeated business heading; loading closes export options',async()=>{
 const {h,reads}=setup();reads[0].resolve(report);await h.flush();assert.match(h.text(),/Status/);assert.match(h.text(),/Complete/);assert.doesNotMatch(h.text(),/Salon/);
 h.click('Export Report');assert.ok(h.button('Detailed Timesheet CSV'));h.click('Monthly');assert.equal(h.button('Detailed Timesheet CSV'),undefined);assert.equal(h.button('Export Report').props.disabled,true);h.dispose();
});
