const {test}=require('node:test');const assert=require('node:assert/strict');const {screen,load,ApiError}=require('./support/native-management.cjs');
const issue={id:'i',employee_id:'e',employee_name:'Employee',note:'Original report',work_date:'2026-03-03',created_at:'2026-03-03T12:00:00Z',status:'open'};
const detail={issue,timesheet:{timezone:'UTC',totals:{workedMs:3600000},days:[{date:'2026-03-03',workedMs:3600000,shifts:[]}]},recentCorrections:[],referencedEventVoided:false};
function setup(){const calls=[];const api={issueMessage:()=> 'Please refresh',getIssues:(business,status,cursor,signal)=>new Promise((resolve,reject)=>calls.push({kind:'list',business,status,cursor,signal,resolve,reject})),getIssue:(business,id,signal)=>new Promise((resolve,reject)=>calls.push({kind:'detail',business,id,signal,resolve,reject})),resolveIssue:(business,user,id,intent,signal)=>new Promise((resolve,reject)=>calls.push({kind:'resolve',business,user,id,intent,signal,resolve,reject}))};const h=screen('features/management/TimeIssuesScreen.tsx',{'../../lib/time-issues-api':api});return {h,calls};}
async function ready(){const x=setup();x.calls[0].resolve({issues:[issue],nextCursor:null});await x.h.flush();x.h.click('View report from Employee');x.calls[1].resolve(detail);await x.h.flush();return x;}
test('Issues native resolution requires note/review/confirm and retries exact uncertain intent',async()=>{const {h,calls}=await ready();assert.equal(h.button('Review resolution').props.disabled,true);h.field('Resolution note','Reviewed with employee');h.click('Review resolution');assert.equal(calls.length,2);h.click('Confirm resolution');assert.equal(calls.length,3);const intent=calls[2].intent;calls[2].reject(new ApiError(0,'NETWORK_ERROR'));await h.flush();h.click('Retry same resolution');assert.deepEqual(calls[3].intent,intent);h.dispose();});
for(const change of ['lock','business','role','logout','background','blur'])test(`Issues ${change} clears sensitive drafts, aborts writes, ignores late success`,async()=>{const {h,calls}=await ready();h.field('Resolution note','Sensitive draft');h.click('Review resolution');h.click('Confirm resolution');if(change==='lock')h.context.identity=null;if(change==='business')h.context.business={id:'other',name:'Other'};if(change==='role')h.context.managementRole='staff';if(change==='logout')h.context.userId=null;if(change==='background')h.background('background');if(change==='blur')h.focus(false);h.render();assert.equal(calls[2].signal.aborted,true);assert.doesNotMatch(h.text(),/Sensitive draft|Original report/);const n=calls.length;calls[2].resolve({id:'r'});await h.flush();assert.equal(calls.length,n);h.dispose();});
test('Issues late detail cannot replace another selection; errors allow refresh',async()=>{const {h,calls}=setup();calls[0].resolve({issues:[issue,{...issue,id:'j',employee_name:'Other'}],nextCursor:null});await h.flush();h.click('View report from Employee');h.click('View report from Other');assert.equal(calls[1].signal.aborted,true);calls[1].resolve(detail);await h.flush();assert.doesNotMatch(h.text(),/Current time interpretation/);calls[2].reject(new ApiError(503,'TIME_LEDGER_CHANGED'));await h.flush();assert.match(h.text(),/Please refresh/);h.dispose();});
test('Issues resolved history is read-only; correction uses the existing panel',async()=>{const {h}=await ready();h.click('Correct time');assert.ok(h.nodes().some(n=>n.type==='CorrectionPanel'));h.dispose();const x=setup();x.calls[0].resolve({issues:[{...issue,status:'resolved'}],nextCursor:null});await x.h.flush();x.h.click('View report from Employee');x.calls[1].resolve({...detail,issue:{...issue,status:'resolved',resolution:{note:'Resolved',recordedAt:issue.created_at}}});await x.h.flush();assert.equal(x.h.button('Correct time'),undefined);assert.equal(x.h.button('Review resolution'),undefined);x.h.dispose();});
test('Management navigation requires both account role and PIN permission',()=>{const nav=load('navigation/items.ts');for(const role of ['manager','owner'])assert.ok(nav.visibleNavigation(role).flatMap(g=>g.items).some(i=>i.route==='/time-issues'));assert.ok(!nav.visibleNavigation('owner',[]).flatMap(g=>g.items).some(i=>i.route==='/time-issues'));});
