const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,require:n=>imports[n],process:{env:{NEXT_PUBLIC_SUPABASE_URL:'test',NEXT_PUBLIC_SUPABASE_ANON_KEY:'test'}},console:{error(){}}});return exports;}
const validation=load('lib/onboarding.ts');
function draft(){const d=validation.newOnboardingDraft();d.name='Test';d.services[0].name='Service';return d;}
test('optional contacts and price accepted',()=>assert.doesNotThrow(()=>validation.validateOnboarding(draft())));
for(const mutate of [d=>d.name='',d=>d.hours.monday.close='08:00',d=>d.hours.monday.closed='false',d=>d.services=[],d=>d.services[0].duration='0',d=>d.services[0].duration='1.5',d=>d.services[0].price='-1',d=>d.greeting=''])test('invalid setup rejected',()=>{const d=draft();mutate(d);assert.throws(()=>validation.validateOnboarding(d));});
function api({user=true,result={success:true},error=null}={}){const calls=[];const route=load('app/api/onboarding/route.ts',{'@/lib/onboarding':validation,'next/server':{NextResponse:{json:(body,options)=>({body,status:options?.status||200})}},'@supabase/supabase-js':{createClient:(_url,_key,options)=>{calls.push(options);return{auth:{getUser:async()=>({data:{user:user?{}:null}})},rpc:async(name,args)=>{calls.push({name,args});return{data:result,error}}}}}});return{calls,post:(body=draft(),token=true)=>route.POST({headers:{get:()=>token?'Bearer test-token':null},json:async()=>body})};}
test('missing/invalid auth blocks provisioning',async()=>{for(const h of [api({user:false}),api()]){const r=await h.post(draft(),false);assert.equal(r.status,401);assert.equal(h.calls.length,0);}assert.equal((await api({user:false}).post()).status,401);});
test('caller JWT attached; browser identities never forwarded',async()=>{const h=api();const r=await h.post({...draft(),user_id:'untrusted',business_id:'untrusted'});assert.equal(r.body.success,true);assert.equal(h.calls[0].global.headers.Authorization,'Bearer test-token');assert.equal(h.calls[1].name,'create_business_for_current_user');assert.equal(h.calls[1].args.p_setup.user_id,undefined);assert.equal(h.calls[1].args.p_setup.business_id,undefined);});
test('invalid draft never invokes RPC',async()=>{const h=api();assert.equal((await h.post({...draft(),services:[]})).status,400);assert.equal(h.calls.length,1);});
test('duplicate setup reconciles without reporting a new creation',async()=>{const r=await api({result:{success:false,code:'ALREADY_PROVISIONED'}}).post();assert.equal(r.status,409);assert.equal(r.body.code,'ALREADY_PROVISIONED');assert.equal(r.body.success,undefined);});
test('failed provisioning never reports success or leaks errors',async()=>{for(const opts of [{error:{message:'private'}},{result:{success:false,code:'INTERNAL_ERROR'}},{result:{success:false,code:'INVALID_SETUP'}}]){const r=await api(opts).post();assert.ok(r.status>=400);assert.notEqual(r.body.success,true);assert.ok(!JSON.stringify(r).includes('private'));}});
const sql=fs.readFileSync('supabase/migrations/202609150001_secure_business_onboarding.sql','utf8');
test('SQL contract: auth-owned bootstrap, serialized duplicate guard, atomic exception boundary',()=>{assert.match(sql,/v_user uuid := auth.uid\(\)/);assert.ok(sql.indexOf('pg_advisory_xact_lock')<sql.indexOf('if exists'));assert.ok(sql.indexOf('ALREADY_PROVISIONED')<sql.indexOf('insert into public.businesses'));assert.match(sql,/values \(v_business, v_user, 'owner'\)/);assert.match(sql,/security definer\s+set search_path = pg_catalog, public/);assert.match(sql,/from public, anon/);assert.match(sql,/to authenticated/);assert.equal((sql.match(/if not found then raise exception/g)||[]).length,5);assert.ok(!/disable row level|create policy/i.test(sql));});
test('SQL contract: profile, services and AI settings use only generated business and auth user',()=>{for(const table of ['business_profiles','services','ai_settings'])assert.match(sql,new RegExp(`insert into public.${table}[\\s\\S]*?values \\(v_business, v_user`));});
const page=fs.readFileSync('app/onboarding/page.tsx','utf8'),provider=fs.readFileSync('components/layout/ActiveBusinessProvider.tsx','utf8');
test('routing contract: anonymous login, zero memberships onboarding, existing onboarding visitor dashboard',()=>{assert.match(provider,/if \(!userId\) \{\s*router.replace\("\/login"\)/);assert.match(provider,/if \(!memberships\?\.length\)[\s\S]*?router.replace\("\/onboarding"\)/);assert.match(provider,/if \(isOnboarding\) router.replace\("\/dashboard"\)/);});
test('wizard contract: duplicate latch, explicit success, draft persistence, fresh membership discovery',()=>{assert.match(page,/if \(submitting.current\) return/);assert.match(page,/response.ok && result.success === true/);assert.match(page,/sessionStorage.setItem/);assert.match(page,/window.location.assign\('\/dashboard'\)/);assert.match(page,/ALREADY_PROVISIONED/);});

test('corrupt saved drafts are rejected before render',()=>{assert.equal(validation.isOnboardingDraft({...draft(),services:[null]}),false);assert.equal(validation.isOnboardingDraft({...draft(),hours:{}}),false);assert.equal(validation.isOnboardingDraft(draft()),true);});
test('SQL rejects stale-snapshot isolation before provisioning lock',()=>{assert.ok(sql.indexOf("current_setting('transaction_isolation')")<sql.indexOf('pg_advisory_xact_lock'));assert.match(sql,/UNSUPPORTED_ISOLATION/);});
