import { useState } from 'react';
import { Text,View } from 'react-native';
import { Button,styles as ui } from '../../components/ui';
import { LabeledField,recordStyles as rs } from '../../components/records';
import { Feedback,SplitWorkspace,PaneTitle,WorkspaceHeader,workspaceStyles as ws } from '../../components/workspace';
import { getAudit,auditMessage } from '../../lib/audit-api';
import { getTimesheetDirectory } from '../../lib/timesheets-api';
import { useManagementScope } from './useManagementScope';
import { useTimeResource } from '../time/useTimeResource';
export function AuditScreen(){const a=useManagementScope();return <View style={ws.page}><WorkspaceHeader title="Audit History" business={a.business.name} subtitle="Recorded management actions"/>{a.scope?<Audit key={a.scope} businessId={a.business.id}/>:<Feedback title="Management access required" detail="Unlock to view audit history."/>}</View>;}
function Audit({businessId}:{businessId:string}){
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[employee,setEmployee]=useState(''),[category,setCategory]=useState(''),[filters,setFilters]=useState<{startDate?:string;endDate?:string;employeeId?:string;category?:string;cursor?:string}>({});
 const directory=useTimeResource(businessId+':audit-employees',signal=>getTimesheetDirectory(businessId,signal));
 const audit=useTimeResource(businessId+JSON.stringify(filters),signal=>getAudit(businessId,filters,signal));
 return <SplitWorkspace main={<><PaneTitle title="Chronological history" detail="Newest first · Account-only records show an account identifier when no historical name was recorded."/>
 <Button label="Refresh" secondary onPress={()=>{directory.refresh();audit.refresh();}}/>{audit.error?<Feedback kind="error" title="History unavailable" detail={auditMessage(audit.error)} retry={audit.refresh}/>:audit.loading?<Feedback kind="loading" title="Loading history"/>:<>
 {!audit.data?.entries.length&&<Feedback title="No recorded actions in this range"/>}{audit.data?.entries.map(e=><View key={e.id} style={rs.block}><Text style={ui.strong}>{e.action.replaceAll('.',' · ').replaceAll('_',' ')} · {e.employee_name??'Team report'}</Text><Text style={ui.meta}>{new Date(e.recorded_at).toLocaleString()} · {e.actor.name??`Account ${e.actor.userId}`} · {e.actor.mode==='shared-device'?'PIN-verified employee':'Account authority'}</Text>{e.reason&&<Text style={ui.body}>{e.reason}</Text>}{e.before_value&&<Text style={ui.meta}>Before: {Object.entries(e.before_value).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v??'none'}`).join(' · ')}</Text>}<Text style={ui.meta}>After: {Object.entries(e.after_value).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v??'none'}`).join(' · ')}</Text>{e.correction_id&&<Text style={ui.meta}>Correction reference: {e.correction_id}</Text>}{e.issue_id&&<Text style={ui.meta}>Issue reference: {e.issue_id}</Text>}{e.pin_reset&&<Text style={ui.meta}>PIN was reset; credential values are never recorded.</Text>}</View>)}
 <View style={rs.actions}>{filters.cursor&&<Button label="First page" secondary onPress={()=>setFilters({...filters,cursor:undefined})}/>} {audit.data?.nextCursor&&<Button label="Next page" secondary onPress={()=>setFilters({...filters,cursor:audit.data!.nextCursor!})}/>}</View></>}
 </>} rail={<><PaneTitle title="Filters" detail="Dates are business-local. Default: last 30 days."/><LabeledField label="Start date (YYYY-MM-DD)" value={start} onChangeText={setStart}/><LabeledField label="End date (YYYY-MM-DD)" value={end} onChangeText={setEnd}/><View style={rs.actions}>{['','team','time','reports'].map(c=><Button key={c} label={c||'All categories'} secondary disabled={category===c} onPress={()=>setCategory(c)}/>)}</View><Button label="All authorized employees" secondary disabled={!employee} onPress={()=>setEmployee('')}/>{directory.error?<Feedback kind="error" title="Employee filters unavailable" retry={directory.refresh}/>:!directory.loading&&directory.data?.employees.map(e=><Button key={e.id} label={e.name} secondary disabled={employee===e.id} onPress={()=>setEmployee(e.id)}/>)}<Button label="Apply filters" onPress={()=>setFilters({startDate:start||undefined,endDate:end||undefined,employeeId:employee||undefined,category:category||undefined})}/></>}/>;
}
